import {
  Alert,
  Box,
  Button,
  Card,
  CardActionArea,
  CardContent,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Divider,
  FormControlLabel,
  List,
  ListItemButton,
  ListItemText,
  MenuItem,
  Stack,
  Switch,
  TextField,
  Typography,
} from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from 'react-router-dom'
import { EmptyState } from '../../../components/feedback/EmptyState'
import { ErrorState } from '../../../components/feedback/ErrorState'
import { LoadingState } from '../../../components/feedback/LoadingState'
import { PageHeader } from '../../../components/tables/DataTable'
import { formatLiters, formatQuantity } from '../../../utils/format'
import { farmDeliveriesApi, type FarmTodayDelivery } from '../api/farmDeliveriesApi'
import { useMyFarm } from '../hooks/useMyFarm'

function toLocalDate(d = new Date()) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate())
}

function dateIso(d: Date) {
  const local = toLocalDate(d)
  const y = local.getFullYear()
  const m = String(local.getMonth() + 1).padStart(2, '0')
  const day = String(local.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

function addDays(d: Date, n: number) {
  const next = toLocalDate(d)
  next.setDate(next.getDate() + n)
  return next
}

function formatGeneratedAt(iso: string | null | undefined) {
  if (!iso) return null
  try {
    return new Intl.DateTimeFormat('en-IN', {
      timeZone: 'Asia/Kolkata',
      dateStyle: 'medium',
      timeStyle: 'short',
    }).format(new Date(iso))
  } catch {
    return iso
  }
}

function formatChipDate(d: Date) {
  return new Intl.DateTimeFormat('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  }).format(d)
}

function isCustomerNoMilk(d: FarmTodayDelivery) {
  if (d.status !== 'SKIPPED') return false
  return String(d.deliveryNotes ?? '').includes('Customer:')
}

function collapseFarmDayRows(rows: FarmTodayDelivery[]) {
  const out: FarmTodayDelivery[] = []
  const seenNoMilk = new Set<string>()
  for (const d of rows) {
    if (!isCustomerNoMilk(d)) {
      out.push(d)
      continue
    }
    const key = `${d.customerId}|${d.deliveryDate ?? ''}`
    if (seenNoMilk.has(key)) continue
    seenNoMilk.add(key)
    out.push(d)
  }
  return out
}

export function FarmTodayDeliveriesPage() {
  const { t } = useTranslation()
  const { farmId, isLoading: farmLoading } = useMyFarm()
  const queryClient = useQueryClient()
  const navigate = useNavigate()
  const today = useMemo(() => toLocalDate(), [])
  const yesterday = useMemo(() => addDays(today, -1), [today])
  const tomorrow = useMemo(() => addDays(today, 1), [today])
  const weekEnd = useMemo(() => addDays(today, 6), [today])
  const todayIso = useMemo(() => dateIso(today), [today])
  const yesterdayIso = useMemo(() => dateIso(yesterday), [yesterday])
  const tomorrowIso = useMemo(() => dateIso(tomorrow), [tomorrow])
  const weekEndIso = useMemo(() => dateIso(weekEnd), [weekEnd])

  const [fromDate, setFromDate] = useState(todayIso)
  const [toDate, setToDate] = useState(todayIso)
  const [dayPickerOpen, setDayPickerOpen] = useState(false)
  const isToday = fromDate === todayIso && toDate === todayIso
  const isYesterday = fromDate === yesterdayIso && toDate === yesterdayIso
  const isTomorrow = fromDate === tomorrowIso && toDate === tomorrowIso
  const isThisWeek = fromDate === todayIso && toDate === weekEndIso
  const isSingleDay = fromDate === toDate
  const rangeLabel = isSingleDay
    ? formatChipDate(new Date(`${fromDate}T00:00:00`))
    : `${formatChipDate(new Date(`${fromDate}T00:00:00`))} – ${formatChipDate(new Date(`${toDate}T00:00:00`))}`

  const setDay = (iso: string) => {
    setFromDate(iso)
    setToDate(iso)
  }
  const setThisWeek = () => {
    setFromDate(todayIso)
    setToDate(weekEndIso)
  }

  const autoGeneratedFor = useRef(new Set<string>())

  const [cashTarget, setCashTarget] = useState<FarmTodayDelivery | null>(null)
  const [cashAmount, setCashAmount] = useState('')
  const [cashPurpose, setCashPurpose] = useState<'BILL_PAYMENT' | 'ADVANCE_PAYMENT'>(
    'BILL_PAYMENT',
  )

  const query = useQuery({
    queryKey: ['farm', 'deliveries', 'today', fromDate, toDate],
    queryFn: () => farmDeliveriesApi.today({ from: fromDate, to: toDate }),
    enabled: Boolean(farmId),
  })

  const statusQuery = useQuery({
    queryKey: ['farm', 'deliveries', 'daily-list-status', farmId, fromDate],
    queryFn: () => farmDeliveriesApi.dailyListStatus(farmId!, fromDate),
    enabled: Boolean(farmId),
  })

  const invalidate = async () => {
    await Promise.all([
      queryClient.invalidateQueries({
        queryKey: ['farm', 'deliveries', 'today', fromDate, toDate],
      }),
      queryClient.invalidateQueries({
        queryKey: ['farm', 'deliveries', 'daily-list-status', farmId, fromDate],
      }),
    ])
    await queryClient.refetchQueries({
      queryKey: ['farm', 'deliveries', 'today', fromDate, toDate],
    })
  }

  const generateMutation = useMutation({
    mutationFn: async () => {
      const days: string[] = []
      const start = new Date(`${fromDate}T00:00:00`)
      const end = new Date(`${toDate}T00:00:00`)
      for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
        days.push(dateIso(d))
      }
      let created = 0
      let skipped = 0
      for (const day of days) {
        const res = await farmDeliveriesApi.generateDailyList(farmId!, day)
        created += Number(res.created ?? 0)
        skipped += Number(res.skipped ?? 0)
      }
      return { created, skipped }
    },
    onSuccess: () => void invalidate(),
  })

  const autoGenerateMutation = useMutation({
    mutationFn: (enabled: boolean) =>
      farmDeliveriesApi.updateDeliverySettings(farmId!, {
        autoGenerateDailyList: enabled,
      }),
    onSuccess: () => void invalidate(),
  })

  const actionMutation = useMutation({
    mutationFn: async ({
      id,
      action,
      quantity,
    }: {
      id: string
      action: 'out' | 'delivered' | 'skip' | 'fail'
      quantity?: string
    }) => {
      if (action === 'out') return farmDeliveriesApi.outForDelivery(id)
      if (action === 'delivered') return farmDeliveriesApi.markDelivered(id, quantity)
      if (action === 'skip') return farmDeliveriesApi.skip(id)
      return farmDeliveriesApi.fail(id)
    },
    onSuccess: () => void invalidate(),
  })

  const skipTodayMutation = useMutation({
    mutationFn: (payload?: { customerId?: string }) =>
      farmDeliveriesApi.skipToday(farmId!, {
        date: fromDate,
        ...(payload?.customerId ? { customerId: payload.customerId } : {}),
      }),
    onSuccess: async (res) => {
      await invalidate()
      window.alert(t('notifiedCustomersSkipped', { n: res.skipped }))
    },
  })

  const confirmCantDeliver = (customerId?: string, customerName?: string) => {
    if (!farmId) return
    if (!isSingleDay) {
      window.alert(t('selectDay'))
      return
    }
    const forOne = Boolean(customerId)
    const ok = window.confirm(
      forOne
        ? `${t('cantDeliver')} · ${customerName ?? t('customer')} · ${rangeLabel}?`
        : `${t('cantDeliver')} · ${rangeLabel}?`,
    )
    if (!ok) return
    skipTodayMutation.mutate(customerId ? { customerId } : undefined)
  }

  const addExtraMutation = useMutation({
    mutationFn: ({
      id,
      extraQuantity,
    }: {
      id: string
      extraQuantity: string
    }) => farmDeliveriesApi.addExtra(id, extraQuantity, undefined, { replace: true }),
    onSuccess: () => void invalidate(),
  })

  const cashMutation = useMutation({
    mutationFn: () =>
      farmDeliveriesApi.recordCashPayment({
        customerId: cashTarget!.customerId,
        farmId: farmId ?? undefined,
        amount: cashAmount.trim(),
        purpose: cashPurpose,
        paymentDate: cashTarget?.deliveryDate ?? fromDate,
        clientReferenceId: crypto.randomUUID(),
      }),
    onSuccess: () => {
      setCashTarget(null)
      setCashAmount('')
    },
  })

  useEffect(() => {
    if (!farmId || query.isLoading || query.isError) return
    if (!isToday) return
    const rows = query.data ?? []
    if (
      rows.length > 0 ||
      autoGeneratedFor.current.has(fromDate) ||
      generateMutation.isPending
    ) {
      return
    }
    // Morning open: build today's list automatically.
    autoGeneratedFor.current.add(fromDate)
    generateMutation.mutate(undefined, {
      onError: () => {
        autoGeneratedFor.current.delete(fromDate)
      },
    })
    // ponytail: once-per-date auto-generate; remount resets the set
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [farmId, fromDate, isToday, query.data, query.isLoading, query.isError])

  const pickDate = () => {
    const raw = window.prompt(t('pickDate'), fromDate)
    if (!raw) return
    if (!/^\d{4}-\d{2}-\d{2}$/.test(raw)) {
      window.alert(t('error'))
      return
    }
    setDay(raw)
  }

  if (farmLoading || (query.isLoading && !query.data)) {
    return <LoadingState label={t('loading')} />
  }
  if (query.isError) {
    return (
      <ErrorState
        title={t('couldNotLoad')}
        message={(query.error as Error).message}
        onRetry={() => void query.refetch()}
      />
    )
  }

  const rows = collapseFarmDayRows(query.data ?? [])
  const status = statusQuery.data
  const lastGeneratedLabel = formatGeneratedAt(status?.lastGeneratedAt)
  const notGenerated = status ? !status.generated : rows.length === 0

  const markDelivered = async (d: FarmTodayDelivery) => {
    const need =
      Number(d.scheduledQuantity || 0) + Number(d.customerExtraQuantity || 0)
    const defaultQty = formatQuantity(String(need || 1))
    const qty = window.prompt(
      `${t('quantityL')} · ${defaultQty === '—' ? need : defaultQty}`,
      defaultQty === '—' ? '1' : defaultQty,
    )
    if (!qty?.trim()) return
    try {
      await actionMutation.mutateAsync({
        id: d.id,
        action: 'delivered',
        quantity: qty.trim(),
      })
    } catch {
      // mutation surfaces via disabled buttons / query refresh
    }
  }

  const openCash = (d: FarmTodayDelivery) => {
    setCashAmount('')
    setCashPurpose('BILL_PAYMENT')
    setCashTarget(d)
  }

  const addExtra = async (d: FarmTodayDelivery) => {
    const current = String(d.staffExtraQuantity ?? '0')
    const qty = window.prompt(
      t('extraMilk'),
      current,
    )
    if (qty == null) return
    const trimmed = qty.trim().replace(',', '.')
    const n = Number(trimmed)
    if (!Number.isFinite(n) || n < 0) {
      window.alert(t('enterValidAmount'))
      return
    }
    await addExtraMutation.mutateAsync({ id: d.id, extraQuantity: trimmed })
  }

  return (
    <Box>
      <PageHeader
        title={t('deliveries')}
        subtitle={t(isSingleDay ? 'fullDayLabel' : 'scheduleLabel', { label: rangeLabel })}
        actions={
          <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
            <Button
              variant="outlined"
              color="error"
              onClick={() => confirmCantDeliver()}
              disabled={!farmId || skipTodayMutation.isPending}
            >
              {skipTodayMutation.isPending ? t('updating') : t('cantDeliver')}
            </Button>
            <Button
              variant="contained"
              onClick={() => generateMutation.mutate()}
              disabled={!farmId || generateMutation.isPending}
            >
              {generateMutation.isPending ? t('generating') : t('generateList')}
            </Button>
          </Stack>
        }
      />

      <Typography variant="body2" color="text.secondary" fontWeight={600} sx={{ mb: 1 }}>
        {t('day')}
      </Typography>
      <Button
        variant="outlined"
        onClick={() => setDayPickerOpen(true)}
        sx={{ mb: 2, justifyContent: 'space-between', minWidth: 280 }}
        endIcon={<span aria-hidden>▾</span>}
      >
        <Box textAlign="left">
          <Typography variant="body2" fontWeight={700} component="span">
            {isToday
              ? t('datesToday')
              : isTomorrow
                ? t('datesTomorrow')
                : isThisWeek
                  ? t('thisWeek')
                  : isYesterday
                    ? t('datesYesterday')
                    : t('customDay')}
          </Typography>
          <Typography variant="caption" color="text.secondary" display="block">
            {rangeLabel}
          </Typography>
        </Box>
      </Button>
      <Dialog open={dayPickerOpen} onClose={() => setDayPickerOpen(false)} fullWidth maxWidth="xs">
        <DialogTitle>{t('selectDay')}</DialogTitle>
        <DialogContent dividers sx={{ p: 0 }}>
          <List disablePadding>
            {(
              [
                { id: 'today', label: t('datesToday'), onClick: () => setDay(todayIso) },
                { id: 'tomorrow', label: t('datesTomorrow'), onClick: () => setDay(tomorrowIso) },
                { id: 'week', label: t('thisWeek'), onClick: setThisWeek },
                { id: 'yesterday', label: t('datesYesterday'), onClick: () => setDay(yesterdayIso) },
              ] as const
            ).map((o) => (
              <ListItemButton
                key={o.id}
                selected={
                  (o.id === 'today' && isToday) ||
                  (o.id === 'tomorrow' && isTomorrow) ||
                  (o.id === 'week' && isThisWeek) ||
                  (o.id === 'yesterday' && isYesterday)
                }
                onClick={() => {
                  o.onClick()
                  setDayPickerOpen(false)
                }}
              >
                <ListItemText primary={o.label} />
              </ListItemButton>
            ))}
          </List>
          <Divider />
          <Box sx={{ p: 2 }}>
            <Button
              fullWidth
              variant="contained"
              onClick={() => {
                setDayPickerOpen(false)
                pickDate()
              }}
            >
              {t('pickDate')}
            </Button>
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDayPickerOpen(false)}>{t('close')}</Button>
        </DialogActions>
      </Dialog>

      {status ? (
        <Stack
          direction={{ xs: 'column', sm: 'row' }}
          spacing={1}
          alignItems={{ xs: 'flex-start', sm: 'center' }}
          justifyContent="space-between"
          sx={{ mb: 2 }}
        >
          <Typography variant="body2" color="text.secondary">
            {lastGeneratedLabel
              ? t('lastGenerated', { when: lastGeneratedLabel })
              : t('notGeneratedYet')}
            {' · '}{t('autoGenerateDailyList')}
          </Typography>
          <FormControlLabel
            control={
              <Switch
                checked={status.autoGenerateDailyList}
                disabled={!farmId || autoGenerateMutation.isPending}
                onChange={(_, checked) => autoGenerateMutation.mutate(checked)}
              />
            }
            label={t('autoGenerateDailyList')}
          />
        </Stack>
      ) : null}

      {notGenerated ? (
        <Alert
          severity="warning"
          sx={{ mb: 2 }}
          action={
            <Button
              color="inherit"
              size="small"
              disabled={!farmId || generateMutation.isPending}
              onClick={() => generateMutation.mutate()}
            >
              {t('generateList')}
            </Button>
          }
        >
          {t('noDeliveryListYet')} · {t('tapGenerateListHint')}
        </Alert>
      ) : null}

      {generateMutation.isSuccess ? (
        <Alert severity="success" sx={{ mb: 2 }}>
          {t('createdSkippedSummary', {
            created: generateMutation.data.created,
            skipped: generateMutation.data.skipped,
          })}
        </Alert>
      ) : null}
      {generateMutation.isError ? (
        <Alert severity="error" sx={{ mb: 2 }}>
          {(generateMutation.error as Error).message}
        </Alert>
      ) : null}

      {rows.length === 0 ? (
        <EmptyState
          title={t('noCustomersToDeliver')}
          description={t('tapGenerateListHint')}
          action={
            <Button
              variant="contained"
              onClick={() => generateMutation.mutate()}
              disabled={!farmId || generateMutation.isPending}
            >
              {t('generateList')}
            </Button>
          }
        />
      ) : (
        <Stack spacing={2}>
          {rows.filter(isCustomerNoMilk).length > 0 ? (
            <Alert severity="error">
              {t('customersDontWantMilk', {
                count: rows.filter(isCustomerNoMilk).length,
                day: isSingleDay ? rangeLabel : t('period'),
              })}
            </Alert>
          ) : null}
          {[...rows]
            .sort((a, b) => Number(isCustomerNoMilk(b)) - Number(isCustomerNoMilk(a)))
            .map((d) => {
            const extra =
              Number(d.customerExtraQuantity || 0) + Number(d.staffExtraQuantity || 0)
            const canAct = d.status === 'PENDING' || d.status === 'OUT_FOR_DELIVERY'
            const canAddExtra =
              d.status === 'PENDING' ||
              d.status === 'OUT_FOR_DELIVERY' ||
              d.status === 'DELIVERED'
            const customerNoMilk = isCustomerNoMilk(d)
            const openDate = d.deliveryDate || fromDate
            return (
              <Card
                key={d.id}
                variant="outlined"
                sx={
                  customerNoMilk
                    ? {
                        borderColor: 'error.main',
                        bgcolor: 'error.50',
                      }
                    : undefined
                }
              >
                <CardActionArea
                  onClick={() =>
                    navigate(`/farm/today/${d.customerId}?date=${openDate}`)
                  }
                >
                  <CardContent sx={{ pb: 1 }}>
                    <Stack
                      direction={{ xs: 'column', sm: 'row' }}
                      justifyContent="space-between"
                      alignItems={{ xs: 'flex-start', sm: 'center' }}
                      spacing={2}
                    >
                      <Box>
                        <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap">
                          <Typography
                            fontWeight={700}
                            color={customerNoMilk ? 'error.main' : undefined}
                          >
                            {d.customerName ?? t('customer')}
                          </Typography>
                          {customerNoMilk ? (
                            <Chip label={t('noMilk')} size="small" color="error" />
                          ) : (
                            <>
                              {!d.customerUserId ? (
                                <Chip label={t('managed')} size="small" />
                              ) : null}
                              <Chip label={d.status} size="small" />
                              {d.isEdited ? (
                                <Chip label={t('edit')} size="small" color="warning" />
                              ) : null}
                            </>
                          )}
                        </Stack>
                        {customerNoMilk ? (
                          <Typography variant="body2" color="error" sx={{ mt: 0.5 }} fontWeight={600}>
                            {t('customerDoesNotWantMilk')}
                          </Typography>
                        ) : null}
                        <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                          {formatLiters(d.expectedQuantity ?? d.scheduledQuantity)} ·{' '}
                          {d.deliveryShift}
                          {extra > 0 ? ` · ${t('extra')} ${formatLiters(extra)}` : ''}
                          {d.mobileNumber ? ` · ${d.mobileNumber}` : ''}
                        </Typography>
                        {d.address ? (
                          <Typography variant="body2" color="text.secondary">
                            {d.address}
                          </Typography>
                        ) : null}
                      </Box>
                      <Typography color="text.secondary">{t('openArrow')}</Typography>
                    </Stack>
                  </CardContent>
                </CardActionArea>
                {canAct || canAddExtra || d.status === 'DELIVERED' ? (
                  <Box sx={{ px: 2, pb: 2 }}>
                    <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap">
                      {d.status === 'PENDING' ? (
                        <Button
                          size="small"
                          variant="outlined"
                          disabled={actionMutation.isPending || addExtraMutation.isPending}
                          onClick={() => actionMutation.mutate({ id: d.id, action: 'out' })}
                        >
                          {t('out')}
                        </Button>
                      ) : null}
                      {canAddExtra ? (
                        <Button
                          size="small"
                          variant="outlined"
                          disabled={actionMutation.isPending || addExtraMutation.isPending}
                          onClick={() => void addExtra(d)}
                        >
                          {t('extra')}
                        </Button>
                      ) : null}
                      {canAct ? (
                        <Button
                          size="large"
                          variant="contained"
                          color="success"
                          disabled={actionMutation.isPending || addExtraMutation.isPending}
                          onClick={() => markDelivered(d)}
                          sx={{ flexGrow: 1, fontWeight: 800, minHeight: 48 }}
                        >
                          {t('markDelivered')}
                        </Button>
                      ) : null}
                      {d.status === 'DELIVERED' && d.customerId ? (
                        <Button
                          size="small"
                          variant="outlined"
                          disabled={cashMutation.isPending}
                          onClick={() => openCash(d)}
                        >
                          {t('recordCash')}
                        </Button>
                      ) : null}
                      {canAct ? (
                        <Button
                          size="small"
                          color="warning"
                          disabled={actionMutation.isPending || skipTodayMutation.isPending}
                          onClick={() =>
                            confirmCantDeliver(d.customerId, d.customerName ?? undefined)
                          }
                        >
                          {t('cantDeliver')}
                        </Button>
                      ) : null}
                      {canAct ? (
                        <Button
                          size="small"
                          color="error"
                          disabled={actionMutation.isPending}
                          onClick={() => actionMutation.mutate({ id: d.id, action: 'fail' })}
                        >
                          {t('fail')}
                        </Button>
                      ) : null}
                    </Stack>
                  </Box>
                ) : null}
              </Card>
            )
          })}
        </Stack>
      )}

      <Dialog open={Boolean(cashTarget)} onClose={() => setCashTarget(null)} maxWidth="xs" fullWidth>
        <DialogTitle>{t('recordCash')}</DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ mt: 1 }}>
            <Typography variant="body2" color="text.secondary">
              {t('collected')} · {cashTarget?.customerName ?? t('customer')}
            </Typography>
            <TextField
              label={t('amountInr')}
              value={cashAmount}
              onChange={(e) => setCashAmount(e.target.value)}
              fullWidth
              autoFocus
            />
            <TextField
              select
              label={t('details')}
              value={cashPurpose}
              onChange={(e) =>
                setCashPurpose(e.target.value as 'BILL_PAYMENT' | 'ADVANCE_PAYMENT')
              }
              fullWidth
            >
              <MenuItem value="BILL_PAYMENT">{t('payment')}</MenuItem>
              <MenuItem value="ADVANCE_PAYMENT">{t('advance')}</MenuItem>
            </TextField>
            {cashMutation.isError ? (
              <Alert severity="error">{(cashMutation.error as Error).message}</Alert>
            ) : null}
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setCashTarget(null)}>{t('cancel')}</Button>
          <Button
            variant="contained"
            disabled={!cashAmount.trim() || cashMutation.isPending}
            onClick={() => cashMutation.mutate()}
          >
            {cashMutation.isPending ? t('saving') : t('save')}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
