import { apiGet, apiPatch, apiPost } from '../../../lib/api/client'
import type { FarmCustomerDeliveryDetail } from '../types/farm'

export interface FarmTodayDelivery {
  id: string
  customerId: string
  customerUserId?: string | null
  subscriptionId?: string | null
  status: string
  deliveryShift: string
  deliveryDate?: string
  expectedQuantity?: string
  scheduledQuantity?: string
  customerExtraQuantity?: string
  staffExtraQuantity?: string
  finalDeliveredQuantity?: string | null
  assignedUserId?: string | null
  customerName?: string
  mobileNumber?: string
  address?: string
  amount?: string
  isEdited?: boolean
  editReviewStatus?: string
  deliveryNotes?: string | null
}

export interface DailyListStatus {
  date: string
  generated: boolean
  deliveryCount: number
  lastGeneratedAt: string | null
  lastGeneratedDate: string | null
  autoGenerateDailyList: boolean
}

export interface FarmDeliverySettings {
  farmId: string
  canViewCustomerBalance: boolean
  canViewBillingSummary: boolean
  canRecordCashPayment: boolean
  canViewPaymentHistory: boolean
  deliveryStaffCanApproveExtraRequests: boolean
  autoGenerateDailyList: boolean
  lastDailyListGeneratedAt?: string | null
  lastDailyListGeneratedDate?: string | null
}

export const farmDeliveriesApi = {
  today(params?: {
    date?: string
    from?: string
    to?: string
    status?: string
    shift?: string
  }) {
    return apiGet<FarmTodayDelivery[]>('/deliveries/today', params)
  },
  recordCashPayment(payload: {
    customerId: string
    farmId?: string
    amount: string
    purpose: 'BILL_PAYMENT' | 'ADVANCE_PAYMENT'
    paymentDate: string
    notes?: string
    clientReferenceId: string
  }) {
    return apiPost('/payments/cash', payload)
  },
  dailyListStatus(farmId: string, date?: string) {
    return apiGet<DailyListStatus>(`/farms/${farmId}/deliveries/daily-list-status`, {
      ...(date ? { date } : {}),
    })
  },
  getDeliverySettings(farmId: string) {
    return apiGet<FarmDeliverySettings>(`/farms/${farmId}/delivery-settings`)
  },
  updateDeliverySettings(
    farmId: string,
    payload: Partial<Pick<FarmDeliverySettings, 'autoGenerateDailyList'>>,
  ) {
    return apiPatch<FarmDeliverySettings>(`/farms/${farmId}/delivery-settings`, payload)
  },
  customerDetail(customerId: string) {
    return apiGet<FarmCustomerDeliveryDetail>(
      `/delivery-staff/customers/${customerId}`,
    )
  },
  getDelivery(id: string) {
    return apiGet<FarmTodayDelivery>(`/deliveries/${id}`)
  },
  generateDailyList(farmId: string, date: string, deliveryShift?: string) {
    return apiPost<{ created: number; skipped: number }>(
      `/farms/${farmId}/deliveries/generate-daily-list`,
      { date, ...(deliveryShift ? { deliveryShift } : {}) },
    )
  },
  outForDelivery(id: string) {
    return apiPost<FarmTodayDelivery>(`/deliveries/${id}/out-for-delivery`)
  },
  markDelivered(id: string, quantity?: string) {
    return apiPost<FarmTodayDelivery>(`/deliveries/${id}/delivered`, {
      ...(quantity ? { finalDeliveredQuantity: quantity } : {}),
    })
  },
  addExtra(
    id: string,
    extraQuantity: string,
    reason?: string,
    opts?: { replace?: boolean },
  ) {
    return apiPost<FarmTodayDelivery>(`/deliveries/${id}/add-extra`, {
      extraQuantity,
      ...(opts?.replace ? { replace: true } : {}),
      ...(reason ? { reason } : {}),
    })
  },
  skip(id: string, notes?: string) {
    return apiPost<FarmTodayDelivery>(`/deliveries/${id}/skipped`, {
      ...(notes ? { notes } : {}),
    })
  },
  skipToday(
    farmId: string,
    payload?: { customerId?: string; date?: string; notes?: string },
  ) {
    return apiPost<{ date: string; skipped: number; customerId: string | null }>(
      `/farms/${farmId}/deliveries/skip-today`,
      {
        ...(payload?.customerId ? { customerId: payload.customerId } : {}),
        ...(payload?.date ? { date: payload.date } : {}),
        ...(payload?.notes ? { notes: payload.notes } : {}),
      },
    )
  },
  fail(id: string, notes?: string) {
    return apiPost<FarmTodayDelivery>(`/deliveries/${id}/failed`, {
      ...(notes ? { notes } : {}),
    })
  },
  assignDelivery(subscriptionId: string, assignedDeliveryUserId: string | null) {
    return apiPost(`/subscriptions/${subscriptionId}/assign-delivery`, {
      assignedDeliveryUserId,
    })
  },
}
